### ISSUE TITLE
Tanzu CLI in isolated environments

### ISSUE THREAD

**Issue by MAHDTech** [vmware-tanzu/tanzu-cli#413]
**Overview**

Hi, I am testing the Tanzu CLI in an internet restricted environment and I have a few questions regarding usage, specifically when it comes to plugins.

I am able to successfully use the awesome `isolated-cluster` sub-command to `download-bundle` and `upload-bundle` to an internal harbor registry.

However when it comes to plugins, I would like to configure an internal plugin source as well.

Query: I'm sure there used to be a `create` option for plugin sources but seems no longer the case, is using `update` default now the correct method?

```bash
tanzu plugin source --help
Manage plugin discovery sources. Discovery source provides metadata about the list of available plugins, their supported versions and how to download them.

Usage:
  tanzu plugin source [command]

Available Commands:
  delete      Delete a discovery source
  init        Initialize the discovery source to its default value
  list        List available discovery sources
  update      Update a discovery source configuration

Flags:
  -h, --help   help for source

Use "tanzu plugin source [command] --help" for more information about a command.
```

**Bug description**

```bash
tanzu plugin source update default myinternalregistry.domain.com/tkg/packages/standalone-plugins:v0.29.0_vmware.1
...
[ok] updated discovery source default

# The config-ng.yaml is now updated with the correct source but config.yaml remains the old one, is this correct?
cat ~/.config/tanzu/config.yaml
cat ~/.config/tanzu/config-ng.yaml
```

- Now try and install a plugin group using the internal registry

```bash
tanzu plugin install --group vmware-tkg/default:v2.2.0

Downloading TKG compatibility file from 'projects.registry.vmware.com/tkg/tkg-compatibility'
Error: unable to ensure prerequisites: unable to ensure tkg BOM file: failed to download TKG compatibility file from the registry: failed to list TKG compatibility image tags: Get "https://projects.registry.vmware.com/v2/": dial tcp: lookup projects.registry.vmware.com on 127.0.0.53:53: read udp 127.0.0.1:38574->127.0.0.53:53: i/o timeout
```

**Expected behavior**

The Tanzu CLI will pull plugins from my internal harbor registry instead of attempting to connect to the internet.

Will there be an `isolated-cluster` like command for plugins?

**Steps to reproduce the bug / Relevant debug output**

As above.

**Output of `tanzu version`**

```bash
version: v0.90.1
buildDate: 2023-06-29
sha: 8945351c
```

**Environment where the bug was observed (cloud, OS, etc)**

- Ubuntu Linux 22.04 client
- vSphere  infrastructure provider platform

**Comment by marckhouzam** [comment]
@MAHDTech have you had a chance to look at the new documentation for setting up plugins for Internet-restricted environments?  https://github.com/vmware-tanzu/tanzu-cli/blob/main/docs/quickstart/install.md#installing-and-using-the-tanzu-cli-in-internet-restricted-environments

And you are correct that `tanzu plugin source update` is to be used in Internet-restricted environment (the `create` command has been removed).
As for the plugin sources listed in`config.yaml`, they are no longer used. Only the ones in `config-ng.yaml` are now used.

Finally, I’ma little surprised you are getting a TKG compatibility file error when you do a plugin install. Were you using the CLI v0.90.1 when that happened?

**Comment by MAHDTech** [comment]
Thanks @marckhouzam, I hadn't seen that doc will give it a run now.

> Finally, I’ma little surprised you are getting a TKG compatibility file error when you do a plugin install. Were you using the CLI v0.90.1 when that happened?

yes v0.90.1, but I've only just upgraded from v0.29 or whatever the bundled one with TKG v2.2 was. 

I'm going to start fresh and give the `tanzu plugin download-bundle` method a go and see where we end up.

Cheers.

**Comment by MAHDTech** [comment]
Ok, I've started clean following the provided instructions and was able to download and upload the plugins to an internal registry, lets call it `harbor.internal` 

The part where I seem hit a roadblock is this command.

```bash
tanzu plugin source update default --uri harbor.internal/tanzu_cli/plugins/plugin-inventory:latest
[!] Unable to resolve the plugin discovery image: error getting the image digest: GET https://harbor.internal/v2/tanzu_cli/plugins/plugin-inventory/manifests/latest: UNAUTHORIZED: unauthorized to access repository: tanzu_cli/plugins/plugin-inventory, action: pull: unauthorized to access repository: tanzu_cli/plugins/plugin-inventory, action: pull
[x] : unable to fetch the inventory of discovery 'default' for plugins: plugins discovery image resolution failed. Please check that the repository image URL "harbor.internal/tanzu_cli/plugins/plugin-inventory:latest" is correct 
```

For reference, I have created a project in harbor named `tanzu_cli` and I can use docker to pull the image manually ok.

```bash
docker image pull harbor.internal/tanzu_cli/plugins/plugin-inventory:latest
latest: Pulling from tanzu_cli/plugins/plugin-inventory
13448116925d: Pull complete 
Digest: sha256:2f29089a37295f098787dffda2b455cde2996939664c2c3710cf972fb15cd95f
Status: Downloaded newer image for harbor.internal/tanzu_cli/plugins/plugin-inventory:latest
harbor.internal/tanzu_cli/plugins/plugin-inventory:latest
```

Do I need to specify credentials somewhere, I had assumed the CLI was reading the docker auth config, as the `upload-bundle` command worked successfully without additional config.

```bash
tanzu version
version: v0.90.1
buildDate: 2023-06-29
sha: 8945351c
```

**Comment by marckhouzam** [comment]
Looks like you are doing the right things @MAHDTech.
The CLI should use the docker creds.  Since the CLI uses `imgpkg` behind the scenes, can you try to pull the image using `imgpkg`?

```
imgpkg pull -i harbor.internal/tanzu_cli/plugins/plugin-inventory:latest -o tmp
```

**Comment by MAHDTech** [comment]
I've got a slightly older version of `imgpkg` installed but using it works fine

```bash
imgpkg version v0.36.2

```bash
imgpkg pull -i harbor.internal/tanzu_cli/plugins/plugin-inventory:latest -o tmp
Pulling image 'harbor.internal/tanzu_cli/plugins/plugin-inventory@sha256:2f29089a37295f098787dffda2b455cde2996939664c2c3710cf972fb15cd95f'
Extracting layer 'sha256:13448116925dc0dbf8417681e13c817d80964544162eba668c683f7063dfe9f7' (1/1)

Succeeded
```

**Comment by marckhouzam** [comment]
This is surprising.  Maybe the real host name is causing problems with the CLI? Can you try using an IP address instead of the host name for the URI?

**Comment by MAHDTech** [comment]
Apologies for taking so long to get back to this, I missed it in a sea of notifications.

It was a while ago, but iirc the issue was related to certificates, adding the CA bundle in the right place sorted it out.

The Tanzu CLI has been working well in an isolated-environment 👍🏻
