### ISSUE TITLE
Configure the Tanzu CLI Home

### ISSUE THREAD

**Issue by MAHDTech** [vmware-tanzu/tanzu-cli#620]
**Describe the feature request**

Is there currently a way to change the location where the Tanzu CLI reads configuration values from, other than the default `~/.config/tanzu`

I would love to be able to set different home directory trees like;

```bash
# No variable set, defaults to ~/.config/tanzu

tanzu do-some-stuff

export TANZU_CLI_HOME=~/.config/tanzu-A

tanzu do-some-stuff using config from A

export TANZU_CLI_HOME=~/.config/tanzu-B

tanzu do-some-stuff using config from B
```

**Describe alternative(s) you've considered**

I'm currently using a bit of a hack where I just symlink from my desired location to `~/.config/tanzu` and that works ok for now.

**Additional context**

I currently switch between multiple different environments, sub-environments and lifecycles and although the ability to use contexts and different servers is great there are times where I would love a completely _seperate isolated  file tree_ such as if you need to make a custom overlay test or a short-term modification to correct a bug or use different versions of the plugins concurrently without re-sync etc.

**Comment by marckhouzam** [comment]
What I have seen is people temporarily changing their `$HOME` directory.
You could have `~/tanzu-A/.config` and `~/tanzu-B/.config`.
You can even create a alias to make this transparent:
```
alias tz="HOME=$HOME/tanzu-A tanzu"
```
Seems to work when I tried it:
```
$ alias ttz="HOME=$HOME/tanzu-A tanzu"
$ ttz version
version: v1.2.0-dev
buildDate: 2023-12-22
sha: 21bac41f1
arch: arm64
$ ls -a ~/tanzu-A
.       ..      .config Library
```

But I think the CLI should respect the XDG paths, which, looking at now, I don't think it does...

**Comment by MAHDTech** [comment]
Apologies for the delay in response and thanks.

I ended up going with a similar trick, just using different "environment" directories each with their own config files.

So far its working out.
